[workspace]
resolver = "3"
members = [
    "crates/daemonize",
    "crates/libc",
    "crates/logging",
    "vendor/rpc-genie/rpc-genie",
    "vendor/rpc-genie/rpc-genie-macros",
]

[patch.crates-io]
rpc-genie = { path = "vendor/rpc-genie/rpc-genie" }
rpc-genie-macros = { path = "vendor/rpc-genie/rpc-genie-macros" }

[package]
name = "taskmaster"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal crates
daemonize = { path = "crates/daemonize" }
libc = { path = "crates/libc" }
logging = { path = "crates/logging" }

# External crates
rpc-genie = "0.1"
rustyline = "18"
tokio = { version = "1", features = ["full"] }
thiserror = "2"
serde = { version = "1.0.217", features = ["derive", "rc"] }
serde_yaml = "0.9.34"
mockall = "0.13.1"
derive-getters = "0.5.0"
shell-words = "1.1.0"
signal = "0.7.0"
serde_with = "3.16.1"
toml = "1.1.4"
ron = "0.12.2"

[build-dependencies]
cc = "1.5.1"
