[package]
name = "taskmaster"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/daemonize",
    "crates/libc",
]

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
daemonize = { path = "./crates/daemonize" }
