name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        run: cargo clippy -- -D warnings

  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --all

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: cargo fmt -- --check
